package:
  name: pyloess
  version: "0.1.0"

source:
  md5: 5be00955378999491f162d69e070d0dbbb6c7191
  git_url: https://github.com/tdhopper/pyloess

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gcc

  run:
    - python

test:
  imports:
    - pyloess

about:
  home: https://github.com/tdhopper/pyloess
  license: MIT
  license_file: LICENSE.txt